# Add feature flags to this file, example:
# dpl202_enable_angry_cat_feature: When enabled this will add an angry cat to all pages that will try to catch the mouse pointer
# The key should be lowecase and snake case, and prefixes with the issue number to allow easy identification
dpl_277_enable_general_reception: Enables the general reception endpoints
dpl_277_disable_pacbio_specific_reception: Enables the general reception endpoints
dpl_277_disable_saphyr_specific_reception: Enables the general reception endpoints
dpl_279_ont_libraries_and_pools: Enables ont library and pool endpoints
